"""حساب افتراضي لكل بند (في الخلفية)، وتحويلات المستفيدين، ووجهة الفائض.

Revision ID: 0873550f3102
Revises: d06ce678686c
Create Date: 2026-10-01 09:12:41.069433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '0873550f3102'
down_revision: Union[str, Sequence[str], None] = 'd06ce678686c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('period_key', sa.String(length=10), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('beneficiary_account_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=128), nullable=False),
    sa.Column('beneficiary_iban', sa.String(length=34), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', name='payoutstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_account_id'], ['bank_accounts.id'], name='fk_payouts_beneficiary_account_id'),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], name='fk_payouts_bucket_id'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name='fk_payouts_entity_id'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='fk_payouts_transaction_id'),
    sa.PrimaryKeyConstraint('id', name='pk_payouts'),
    sa.UniqueConstraint('reference', name='uq_payouts_reference')
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payouts_bucket_id'), ['bucket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('virtual_iban', sa.String(length=34), nullable=True))
        batch_op.add_column(sa.Column('virtual_ref', sa.String(length=128), nullable=True))

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surplus_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_policies_surplus_account_id', 'bank_accounts', ['surplus_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_policies_surplus_account_id', type_='foreignkey')
        batch_op.drop_column('surplus_account_id')

    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.drop_column('virtual_ref')
        batch_op.drop_column('virtual_iban')

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payouts_entity_id'))
        batch_op.drop_index(batch_op.f('ix_payouts_created_at'))
        batch_op.drop_index(batch_op.f('ix_payouts_bucket_id'))

    op.drop_table('payouts')
    # ### end Alembic commands ###
