"""approval mode per company

Revision ID: 110d14b80bcb
Revises: 2753f9722b80
Create Date: 2026-09-29 13:49:26.666320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '110d14b80bcb'
down_revision: Union[str, Sequence[str], None] = '2753f9722b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_mode', sa.String(length=16), server_default='reviewer', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_column('approval_mode')

    # ### end Alembic commands ###
