"""initial schema

Revision ID: 2753f9722b80
Revises: 
Create Date: 2026-09-29 11:12:06.459332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '2753f9722b80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'accountant', 'approver', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cr_number', sa.String(length=32), nullable=False),
    sa.Column('vat_number', sa.String(length=32), nullable=False),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('contact_name', sa.String(length=128), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)

    op.create_table('buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buckets_entity_id'), ['entity_id'], unique=False)

    op.create_table('custom_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('fmt', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'name')
    )
    with op.batch_alter_table('custom_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_metrics_entity_id'), ['entity_id'], unique=False)

    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('initialized', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'active', 'archived', 'rejected', name='policystatus', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('submitted_at', app.models.UTCDateTime(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', app.models.UTCDateTime(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'version')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_entity_id'), ['entity_id'], unique=False)

    op.create_table('user_entities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'entity_id')
    )
    op.create_table('bucket_period_state',
    sa.Column('bucket_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('period_key', sa.String(length=10), nullable=False),
    sa.Column('target', sa.BigInteger(), nullable=False),
    sa.Column('funded', sa.BigInteger(), nullable=False),
    sa.Column('carried_deficit', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('bucket_id')
    )
    with op.batch_alter_table('bucket_period_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bucket_period_state_entity_id'), ['entity_id'], unique=False)

    op.create_table('dashboard_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('calc_type', sa.Enum('percentage', 'fixed_amount', name='calctype', native_enum=False, length=20), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('frequency', sa.Enum('immediate', 'daily', 'weekly', 'monthly', 'day_of_month', name='frequency', native_enum=False, length=20), nullable=False),
    sa.Column('settlement_day', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'bucket_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('surplus', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'open_banking', name='transactionsource', native_enum=False, length=20), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('reversal_of', sa.Integer(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['reversal_of'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_ref'),
    sa.UniqueConstraint('reversal_of')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('allocation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=False),
    sa.Column('period_key', sa.String(length=10), nullable=False),
    sa.Column('required', sa.BigInteger(), nullable=False),
    sa.Column('allocated', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('FULLY_FUNDED', 'PARTIAL', 'UNFUNDED', 'NOT_REQUIRED', name='fundingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('funded_after', sa.BigInteger(), nullable=False),
    sa.Column('carried_deficit_after', sa.BigInteger(), nullable=False),
    sa.Column('before_period_key', sa.String(length=10), nullable=True),
    sa.Column('before_target', sa.BigInteger(), nullable=True),
    sa.Column('before_funded', sa.BigInteger(), nullable=True),
    sa.Column('before_carried_deficit', sa.BigInteger(), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allocation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_events_bucket_id'), ['bucket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocation_events_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('period_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=False),
    sa.Column('period_key', sa.String(length=10), nullable=False),
    sa.Column('target', sa.BigInteger(), nullable=False),
    sa.Column('funded', sa.BigInteger(), nullable=False),
    sa.Column('closed_deficit', sa.BigInteger(), nullable=False),
    sa.Column('closed_by_transaction_id', sa.Integer(), nullable=True),
    sa.Column('closed_by_policy_id', sa.Integer(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ),
    sa.ForeignKeyConstraint(['closed_by_policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['closed_by_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('period_closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_closures_bucket_id'), ['bucket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_period_closures_entity_id'), ['entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period_closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_closures_entity_id'))
        batch_op.drop_index(batch_op.f('ix_period_closures_bucket_id'))

    op.drop_table('period_closures')
    with op.batch_alter_table('allocation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_events_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_allocation_events_bucket_id'))

    op.drop_table('allocation_events')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_entity_id'))

    op.drop_table('transactions')
    op.drop_table('policy_buckets')
    op.drop_table('dashboard_widgets')
    with op.batch_alter_table('bucket_period_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bucket_period_state_entity_id'))

    op.drop_table('bucket_period_state')
    op.drop_table('user_entities')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_entity_id'))

    op.drop_table('policies')
    op.drop_table('dashboards')
    with op.batch_alter_table('custom_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_metrics_entity_id'))

    op.drop_table('custom_metrics')
    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buckets_entity_id'))

    op.drop_table('buckets')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    op.drop_table('entities')
    op.drop_table('users')
    # ### end Alembic commands ###
