"""bank accounts

Revision ID: 72c08fe395a3
Revises: f5149bfd607f
Create Date: 2026-09-30 10:06:24.043785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '72c08fe395a3'
down_revision: Union[str, Sequence[str], None] = 'f5149bfd607f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('kind', sa.Enum('source', 'pool', 'sub', 'external', name='accountkind', native_enum=False, length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'iban')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_accounts_iban'), ['iban'], unique=False)

    with op.batch_alter_table('policy_buckets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_policy_buckets_destination_account', 'bank_accounts', ['destination_account_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_source_account', 'bank_accounts', ['source_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_source_account', type_='foreignkey')
        batch_op.drop_column('source_account_id')

    with op.batch_alter_table('policy_buckets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_policy_buckets_destination_account', type_='foreignkey')
        batch_op.drop_column('destination_account_id')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_iban'))
        batch_op.drop_index(batch_op.f('ix_bank_accounts_entity_id'))

    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
