"""policy bucket due date

Revision ID: d06ce678686c
Revises: a23d883e1724
Create Date: 2026-09-30 11:28:32.671488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = 'd06ce678686c'
down_revision: Union[str, Sequence[str], None] = 'a23d883e1724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_buckets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_buckets', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
