"""self signup email

Revision ID: f5149bfd607f
Revises: 110d14b80bcb
Create Date: 2026-09-29 14:17:06.219121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = 'f5149bfd607f'
down_revision: Union[str, Sequence[str], None] = '110d14b80bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('account_type', sa.String(length=16), nullable=True))
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_column('account_type')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
